package controller

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/stackriv/dev-tools/internal/business/model"
	"github.com/stackriv/dev-tools/internal/config"
	"github.com/stackriv/dev-tools/internal/globale"
	"github.com/stackriv/dev-tools/internal/pkg"
)

func Compose(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodGet {
		if r.URL.Path != "/compose" {
			err := pkg.ErrorMessage(http.StatusNotFound)
			config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: err["msg"]}})
			fmt.Println(http.StatusNotFound, err["msg"])
			return
		}

		config.RenderTemplate(w, "compose", model.PageData{
			Title:       "Docker Compose Generator",
			Description: "Generate a docker-compose.yaml for your stack.",
			Page:        "compose",
		})
	}
}

func GenerateCompose(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/api/compose" {
		err := pkg.ErrorMessage(http.StatusNotFound)
		config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: err["msg"]}})
		fmt.Println(http.StatusNotFound, err["msg"])
		return
	}

	w.Header().Set("Content-Type", "application/json")

	var body struct {
		Services []struct {
			Name    string `json:"name"`
			Version string `json:"version"`
		} `json:"services"`
		Network string `json:"network"`
	}

	if err := json.NewDecoder(r.Body).Decode(&body); err != nil || len(body.Services) == 0 {
		err1 := pkg.ErrorMessage(http.StatusBadRequest)
		config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err1["code"], Message: "at least one service required"}})
		fmt.Println(http.StatusNotFound, "at least one service required")
		return
	}

	var sb strings.Builder
	sb.WriteString("# Generated by Stackriv Dev Tools\n\n")
	sb.WriteString("services:\n")

	var volumes []string
	for _, svc := range body.Services {
		if fn, ok := globale.ComposeServices[svc.Name]; ok {
			sb.WriteString(fn(svc.Version))
			if vol, ok := globale.VolumeNames[svc.Name]; ok {
				for _, v := range strings.Split(vol, "\n") {
					v = strings.TrimSpace(v)
					if v != "" {
						volumes = append(volumes, v)
					}
				}
			}
		}
	}

	if len(volumes) > 0 {
		sb.WriteString("\nvolumes:\n")
		seen := map[string]bool{}
		for _, v := range volumes {
			if !seen[v] {
				sb.WriteString(fmt.Sprintf("  %s:\n", v))
				seen[v] = true
			}
		}
	}

	if body.Network != "" {
		sb.WriteString(fmt.Sprintf("\nnetworks:\n  %s:\n    driver: bridge\n", body.Network))
	}

	err := json.NewEncoder(w).Encode(map[string]string{"content": sb.String()})
	if err != nil {
		err1 := pkg.ErrorMessage(http.StatusInternalServerError)
		config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err1["code"], Message: err1["msg"]}})
		fmt.Println(err1)
	}
}
