package controller

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/stackriv/dev-tools/internal/business/model"
	"github.com/stackriv/dev-tools/internal/config"
	"github.com/stackriv/dev-tools/internal/pkg"
)

func DockerfileHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodGet {
		if r.URL.Path != "/dockerfile" {
			err := pkg.ErrorMessage(http.StatusNotFound)
			config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: err["msg"]}})
			fmt.Println(http.StatusNotFound, err["msg"])
			return
		}

		config.RenderTemplate(w, "dockerfile", model.PageData{
			Title:       "Dockerfile Generator",
			Description: "Generate a production-ready Dockerfile for your application.",
			Page:        "dockerfile",
		})
	}
}

func GenerateDockerfile(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/api/dockerfile" {
		err := pkg.ErrorMessage(http.StatusNotFound)
		config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: err["msg"]}})
		fmt.Println(http.StatusNotFound, err["msg"])
		return
	}

	w.Header().Set("Content-Type", "application/json")

	var body struct {
		Lang        string `json:"lang"`
		LangVersion string `json:"langVersion"`
		Port        string `json:"port"`
		Workdir     string `json:"workdir"`
		Multistage  bool   `json:"multistage"`
		NonRoot     bool   `json:"nonroot"`
		Healthcheck bool   `json:"healthcheck"`
	}

	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		err := pkg.ErrorMessage(http.StatusBadRequest)
		config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: "invalid request"}})
		fmt.Println(http.StatusBadRequest, "invalid request")
		return
	}

	if strings.TrimSpace(body.Port) == "" {
		body.Port = "8080"
	}

	if strings.TrimSpace(body.Workdir) == "" {
		body.Workdir = "/app"
	}

	content := generateDockerfile(body.Lang, body.LangVersion, body.Port, body.Workdir, body.Multistage, body.NonRoot, body.Healthcheck)

	err := json.NewEncoder(w).Encode(map[string]string{"content": content})
	if err != nil {
		err := pkg.ErrorMessage(http.StatusInternalServerError)
		config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: err["msg"]}})
		fmt.Println(err)
	}
}

func generateDockerfile(lang, version, port, workdir string, multistage, nonroot, healthcheck bool) string {
	var sb strings.Builder

	sb.WriteString("# Generated by Stackriv Dev Tools\n\n")

	switch lang {
	case "go":
		v := version
		if v == "" {
			v = "1.23"
		}
		if multistage {
			sb.WriteString(fmt.Sprintf("FROM golang:%s-alpine AS builder\n\n", v))
			sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
			sb.WriteString("COPY go.mod go.sum ./\n")
			sb.WriteString("RUN go mod download\n")
			sb.WriteString("COPY . .\n")
			sb.WriteString("RUN CGO_ENABLED=0 GOOS=linux go build -o app .\n\n")
			sb.WriteString("FROM alpine:latest\n")
			sb.WriteString("RUN apk add --no-cache ca-certificates\n")
			sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
			sb.WriteString(fmt.Sprintf("COPY --from=builder %s/app .\n", workdir))
		} else {
			sb.WriteString(fmt.Sprintf("FROM golang:%s-alpine\n\n", v))
			sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
			sb.WriteString("COPY go.mod go.sum ./\n")
			sb.WriteString("RUN go mod download\n")
			sb.WriteString("COPY . .\n")
			sb.WriteString("RUN CGO_ENABLED=0 go build -o app .\n")
		}

	case "node":
		v := version
		if v == "" {
			v = "20"
		}
		if multistage {
			sb.WriteString(fmt.Sprintf("FROM node:%s-alpine AS builder\n\n", v))
			sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
			sb.WriteString("COPY package*.json ./\n")
			sb.WriteString("RUN npm ci\n")
			sb.WriteString("COPY . .\n")
			sb.WriteString("RUN npm run build\n\n")
			sb.WriteString(fmt.Sprintf("FROM node:%s-alpine\n", v))
			sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
			sb.WriteString("COPY package*.json ./\n")
			sb.WriteString("RUN npm ci --only=production\n")
			sb.WriteString(fmt.Sprintf("COPY --from=builder %s/dist ./dist\n", workdir))
		} else {
			sb.WriteString(fmt.Sprintf("FROM node:%s-alpine\n\n", v))
			sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
			sb.WriteString("COPY package*.json ./\n")
			sb.WriteString("RUN npm ci\n")
			sb.WriteString("COPY . .\n")
		}

	case "python":
		v := version
		if v == "" {
			v = "3.12"
		}
		if multistage {
			sb.WriteString(fmt.Sprintf("FROM python:%s-slim AS builder\n\n", v))
			sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
			sb.WriteString("COPY requirements.txt .\n")
			sb.WriteString("RUN pip install --no-cache-dir --user -r requirements.txt\n\n")
			sb.WriteString(fmt.Sprintf("FROM python:%s-slim\n", v))
			sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
			sb.WriteString("COPY --from=builder /root/.local /root/.local\n")
			sb.WriteString("COPY . .\n")
		} else {
			sb.WriteString(fmt.Sprintf("FROM python:%s-slim\n\n", v))
			sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
			sb.WriteString("COPY requirements.txt .\n")
			sb.WriteString("RUN pip install --no-cache-dir -r requirements.txt\n")
			sb.WriteString("COPY . .\n")
		}

	case "java":
		v := version
		if v == "" {
			v = "21"
		}
		sb.WriteString(fmt.Sprintf("FROM maven:3.9-%s AS builder\n\n", fmt.Sprintf("eclipse-temurin-%s", v)))
		sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
		sb.WriteString("COPY pom.xml .\n")
		sb.WriteString("RUN mvn dependency:go-offline\n")
		sb.WriteString("COPY src ./src\n")
		sb.WriteString("RUN mvn package -DskipTests\n\n")
		sb.WriteString(fmt.Sprintf("FROM eclipse-temurin:%s-jre\n", v))
		sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
		sb.WriteString(fmt.Sprintf("COPY --from=builder %s/target/*.jar app.jar\n", workdir))

	case "rust":
		sb.WriteString("FROM rust:alpine AS builder\n\n")
		sb.WriteString("RUN apk add --no-cache musl-dev\n")
		sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
		sb.WriteString("COPY Cargo.toml Cargo.lock ./\n")
		sb.WriteString("COPY src ./src\n")
		sb.WriteString("RUN cargo build --release\n\n")
		sb.WriteString("FROM alpine:latest\n")
		sb.WriteString("RUN apk add --no-cache ca-certificates\n")
		sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
		sb.WriteString(fmt.Sprintf("COPY --from=builder %s/target/release/app .\n", workdir))

	case "php":
		v := version
		if v == "" {
			v = "8.3"
		}
		sb.WriteString(fmt.Sprintf("FROM php:%s-fpm-alpine\n\n", v))
		sb.WriteString("RUN apk add --no-cache nginx\n")
		sb.WriteString(fmt.Sprintf("WORKDIR %s\n", workdir))
		sb.WriteString("COPY . .\n")
		sb.WriteString("RUN composer install --no-dev --optimize-autoloader\n")
	}

	if nonroot {
		sb.WriteString("\n# Non-root user\n")
		sb.WriteString("RUN addgroup -S appgroup && adduser -S appuser -G appgroup\n")
		sb.WriteString("USER appuser\n")
	}

	sb.WriteString(fmt.Sprintf("\nEXPOSE %s\n", port))

	if healthcheck {
		sb.WriteString(fmt.Sprintf("\nHEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\\n  CMD wget -qO- http://localhost:%s/health || exit 1\n", port))
	}

	// CMD selon le langage
	switch lang {
	case "go", "rust":
		sb.WriteString("\nCMD [\"./app\"]\n")
	case "node":
		sb.WriteString("\nCMD [\"node\", \"dist/index.js\"]\n")
	case "python":
		sb.WriteString("\nCMD [\"python\", \"main.py\"]\n")
	case "java":
		sb.WriteString("\nCMD [\"java\", \"-jar\", \"app.jar\"]\n")
	case "php":
		sb.WriteString("\nCMD [\"php-fpm\"]\n")
	}

	return sb.String()
}
