package controller

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/stackriv/dev-tools/internal/business/model"
	"github.com/stackriv/dev-tools/internal/config"
	"github.com/stackriv/dev-tools/internal/globale"
	"github.com/stackriv/dev-tools/internal/pkg"
)

func Env(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodGet {
		if r.URL.Path != "/env" {
			err := pkg.ErrorMessage(http.StatusNotFound)
			config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: err["msg"]}})
			fmt.Println(http.StatusNotFound, err["msg"])
			return
		}

		config.RenderTemplate(w, "env", model.PageData{
			Title:       ".env Generator",
			Description: "Generate a .env template file with common environment variables.",
			Page:        "env",
		})
	}
}

func GenerateEnv(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/api/env" {
		err := pkg.ErrorMessage(http.StatusNotFound)
		config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: err["msg"]}})
		fmt.Println(http.StatusNotFound, err["msg"])
		return
	}

	w.Header().Set("Content-Type", "application/json")

	var body struct {
		Presets []string `json:"presets"`
		AppName string   `json:"appName"`
	}

	if err := json.NewDecoder(r.Body).Decode(&body); err != nil || len(body.Presets) == 0 {
		err := pkg.ErrorMessage(http.StatusBadRequest)
		config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: "presets required"}})
		fmt.Println(http.StatusBadRequest, err["msg"])
		return
	}

	var sb strings.Builder
	appName := body.AppName
	if appName == "" {
		appName = "my-app"
	}

	sb.WriteString(fmt.Sprintf("# .env — %s\n# Generated by Stackriv Dev Tools\n# ⚠️  Never commit this file to version control\n\n", appName))

	for _, preset := range body.Presets {
		if content, ok := globale.EnvPresets[preset]; ok {
			sb.WriteString(content)
			sb.WriteString("\n")
		}
	}

	err := json.NewEncoder(w).Encode(map[string]string{"content": sb.String()})
	if err != nil {
		err := pkg.ErrorMessage(http.StatusInternalServerError)
		config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: err["msg"]}})
		fmt.Println(err)
	}
}
