package controller

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/stackriv/dev-tools/internal/business/model"
	"github.com/stackriv/dev-tools/internal/config"
	"github.com/stackriv/dev-tools/internal/globale"
	"github.com/stackriv/dev-tools/internal/pkg"
)

func Gitignore(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodGet {
		if r.URL.Path != "/gitignore" {
			err := pkg.ErrorMessage(http.StatusNotFound)
			config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: err["msg"]}})
			fmt.Println(http.StatusNotFound, err["msg"])
			return
		}

		config.RenderTemplate(w, "gitignore", model.PageData{
			Title:       ".gitignore Generator",
			Description: "Generate a .gitignore file by selecting your technologies.",
			Page:        "gitignore",
		})
	}
}

func GenerateGitignore(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/api/gitignore" {
		err := pkg.ErrorMessage(http.StatusNotFound)
		config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: err["msg"]}})
		fmt.Println(http.StatusNotFound, err["msg"])
		return
	}

	w.Header().Set("Content-Type", "application/json")
	var body struct {
		Technologies []string `json:"technologies"`
	}

	if err := json.NewDecoder(r.Body).Decode(&body); err != nil || len(body.Technologies) == 0 {
		err := pkg.ErrorMessage(http.StatusBadRequest)
		config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: err["msg"]}})
		fmt.Println(http.StatusBadRequest, err["msg"])
		return
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Generated by Stackriv Dev Tools\n# Technologies: %s\n\n", strings.Join(body.Technologies, ", ")))
	sb.WriteString(globale.CommonGitignore)
	sb.WriteString("\n")

	for _, tech := range body.Technologies {
		if content, ok := globale.GitignoreTemplates[tech]; ok {
			sb.WriteString(content)
		}
		sb.WriteString("\n")
	}

	err := json.NewEncoder(w).Encode(map[string]string{"content": sb.String()})
	if err != nil {
		err := pkg.ErrorMessage(http.StatusInternalServerError)
		config.RenderTemplate(w, "error", model.PageData{Error: model.ErrorData{Code: err["code"], Message: err["msg"]}})
		fmt.Println(err)
	}
}
